<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\MyRecepeBook.Communication\MyRecepeBook.Communication.csproj" />
    <ProjectReference Include="..\..\Shared\MyRecepeBook.Exception\MyRecepeBook.Exception.csproj" />
    <ProjectReference Include="..\MyRecepeBook.Domain\MyRecepeBook.Domain.csproj" />
  </ItemGroup>

</Project>
